[package]
name = "nym-gateway-directory"
version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true
hickory-resolver.workspace = true
itertools.workspace = true
nym-client-core.workspace = true
nym-config.workspace = true
nym-sdk.workspace = true
nym-topology.workspace = true
nym-validator-client.workspace = true
nym-vpn-api-client = { path = "../nym-vpn-api-client" }
rand.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true }
tokio-tungstenite = { version = "0.26.1" }
tungstenite = { version = "0.26.1" }
tracing.workspace = true
url.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
