accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "GPL-3.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "NOASSERTION",
    "OpenSSL",
    "Unicode-DFS-2016",
    "WTFPL",
]

workarounds = [
    "ring",
    "rustls",
]
