[package]
name = "nym-vpn-lib"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
bincode = "1.3.3"
bytes = "1.0"
default-net = "0.21.0"
futures = "0.3.15"
ipnetwork = "0.16"
log = "0.4.20"
rand = "0.7.3"
serde = "1.0.192"
serde_json = "1.0.91"
signature = "1"
tap = "1.0.1"
thiserror = "1.0.38"
tokio = { version = "1.8", features = ["process", "rt-multi-thread", "fs", "sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tun = { version = "0.6.1", features = ["async"] }
url = "2.4"

talpid-core = { git = "https://github.com/mullvad/mullvadvpn-app", tag = "2023.2" }
talpid-platform-metadata = { git = "https://github.com/mullvad/mullvadvpn-app", tag = "2023.2" }
talpid-routing = { git = "https://github.com/mullvad/mullvadvpn-app", tag = "2023.2" }
talpid-tunnel = { git = "https://github.com/mullvad/mullvadvpn-app", tag = "2023.2" }
talpid-types = { git = "https://github.com/mullvad/mullvadvpn-app", tag = "2023.2" }
talpid-wireguard = { git = "https://github.com/mullvad/mullvadvpn-app", tag = "2023.2" }

nym-bin-common = { git = "https://github.com/nymtech/nym", branch = "jon/feat/test-rustls" }
nym-client-core = { git = "https://github.com/nymtech/nym", branch = "jon/feat/test-rustls" }
nym-config = { git = "https://github.com/nymtech/nym", branch = "jon/feat/test-rustls" }
nym-crypto = { git = "https://github.com/nymtech/nym", branch = "jon/feat/test-rustls" }
nym-ip-packet-requests = { git = "https://github.com/nymtech/nym", branch = "jon/feat/test-rustls" }
nym-node-requests = { git = "https://github.com/nymtech/nym", branch = "jon/feat/test-rustls" }
nym-sdk = { git = "https://github.com/nymtech/nym", branch = "jon/feat/test-rustls" }
nym-task = { git = "https://github.com/nymtech/nym", branch = "jon/feat/test-rustls" }
nym-validator-client = { git = "https://github.com/nymtech/nym", branch = "jon/feat/test-rustls" }
nym-wireguard-types = { git = "https://github.com/nymtech/nym", branch = "jon/feat/test-rustls" }
