[package]
name = "nym-vpn-lib"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
anyhow = "1.0.71"
bincode = "1.3.3"
bytes = "1.0"
default-net = "0.21.0"
futures = "0.3.15"
ipnetwork = "0.16"
lazy_static = "1.4.0"
log = "0.4.20"
rand = "0.7.3"
serde = "1.0.192"
serde_json = "1.0.91"
signature = "1"
tap = "1.0.1"
thiserror = "1.0.38"
tokio = { workspace = true, features = ["process", "rt-multi-thread", "fs", "sync"] }
tokio-util = { version = "0.7.10", features = ["codec"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "f5fc9d7e9aa08889aedc45dd81ae9b4d3ec4cbe8", features = ["cli"] }
tun2 = { version = "1.2.3", features = ["async"] }
url = "2.4"

# Used in order to correctly import rustls for sub-dependencies
reqwest = { version = "0.11.22", default_features = false, features = ["rustls-tls"] }
tokio-tungstenite = { version = "0.20.1", features = ["rustls"] }
tungstenite = { version = "0.20.1", default-features = false, features = ["rustls"] }

talpid-core = { git = "https://github.com/nymtech/nym-vpn-mullvad-libs", rev = "fde37701018191d16bc66c37616588aa120b9549" }
talpid-platform-metadata = { git = "https://github.com/nymtech/nym-vpn-mullvad-libs", rev = "fde37701018191d16bc66c37616588aa120b9549" }
talpid-routing = { git = "https://github.com/nymtech/nym-vpn-mullvad-libs", rev = "fde37701018191d16bc66c37616588aa120b9549" }
talpid-tunnel = { git = "https://github.com/nymtech/nym-vpn-mullvad-libs", rev = "fde37701018191d16bc66c37616588aa120b9549" }
talpid-types = { git = "https://github.com/nymtech/nym-vpn-mullvad-libs", rev = "fde37701018191d16bc66c37616588aa120b9549" }
talpid-wireguard = { git = "https://github.com/nymtech/nym-vpn-mullvad-libs", rev = "fde37701018191d16bc66c37616588aa120b9549" }

nym-bin-common = { git = "https://github.com/nymtech/nym", rev = "fa8e81d9dd1e93e133c666ef777757edd7fdce25" }
nym-client-core = { git = "https://github.com/nymtech/nym", rev = "fa8e81d9dd1e93e133c666ef777757edd7fdce25" }
nym-config = { git = "https://github.com/nymtech/nym", rev = "fa8e81d9dd1e93e133c666ef777757edd7fdce25" }
nym-crypto = { git = "https://github.com/nymtech/nym", rev = "fa8e81d9dd1e93e133c666ef777757edd7fdce25" }
nym-ip-packet-requests = { git = "https://github.com/nymtech/nym", rev = "fa8e81d9dd1e93e133c666ef777757edd7fdce25" }
nym-node-requests = { git = "https://github.com/nymtech/nym", rev = "fa8e81d9dd1e93e133c666ef777757edd7fdce25" }
nym-sdk = { git = "https://github.com/nymtech/nym", rev = "fa8e81d9dd1e93e133c666ef777757edd7fdce25" }
nym-task = { git = "https://github.com/nymtech/nym", rev = "fa8e81d9dd1e93e133c666ef777757edd7fdce25" }
nym-validator-client = { git = "https://github.com/nymtech/nym", rev = "fa8e81d9dd1e93e133c666ef777757edd7fdce25" }
nym-wireguard-types = { git = "https://github.com/nymtech/nym", rev = "fa8e81d9dd1e93e133c666ef777757edd7fdce25" }
nym-explorer-client = { git = "https://github.com/nymtech/nym", rev = "fa8e81d9dd1e93e133c666ef777757edd7fdce25" }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.1"
err-derive = "0.3.1"
jnix = { version = "=0.5.0", features = ["derive"] }
nix = "0.23"
rand = "0.8.5"

[target.'cfg(target_os = "macos")'.dependencies]
oslog = "0.2.0"

[build-dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "f5fc9d7e9aa08889aedc45dd81ae9b4d3ec4cbe8", features = ["build"] }
