[versions]
accompanist = "0.34.0"
agp = "8.4.1"
coreSplashscreen = "1.0.1"
detektRulesCompose = "1.3.0"
javaClient = "9.2.2"
jna = "5.14.0"
kotlin = "1.9.23"
ksp = "1.9.23-1.0.19"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
materialIconsExtended = "1.6.7"
navigationCompose = "2.7.7"
hiltNavigationCompose = "1.2.0"
lifecycleRuntimeKtx = "2.7.0"
lifecycle-runtime-compose = "2.7.0"
activityCompose = "1.9.0"
composeBom = "2024.05.00"
datastorePreferences = "1.1.1"
securityCrypto = "1.1.0-alpha06"
timber = "5.0.1"
hiltAndroid = "2.51.1"
kotlinx-serialization-json = "1.6.3"
kotlinxCoroutinesCore = "1.8.0"
uiautomator = "2.3.0"
window = "1.2.0"
windowCoreAndroid = "1.3.0-rc01"
desugar = "2.0.4"
moshi = "1.15.1"
moshiKotlin = "1.15.1"
moshiKotlinCodegen = "1.15.1"
converterMoshi = "2.11.0"
zxingAndroidEmbedded = "4.3.0"

gradlePlugins-kotlinxSerialization = "1.9.23"
gradlePlugins-licensee = "1.7.0"
gradlePlugins-detekt = "1.23.6"
gradlePlugins-gross = "0.1.0"
gradlePlugins-sentry = "4.5.1"
appcompat = "1.6.1"
material = "1.12.0"
gradlePlugins-ktlint="12.1.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
detekt-rules-compose = { module = "ru.kode:detekt-rules-compose", version.ref = "detektRulesCompose" }
java-client = { module = "io.appium:java-client", version.ref = "javaClient" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }


jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle-runtime-compose" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle-runtime-compose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

#retrofit/moshi
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converterMoshi" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshiKotlin" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshiKotlinCodegen" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterMoshi" }

#barcode
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

#util
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
com-android-tools-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

#compose
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }


#storage
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }

#navigation
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-window-core-android = { group = "androidx.window", name = "window-core-android", version.ref = "windowCoreAndroid" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-library = { id = "com.android.library", version.ref = "agp" }
licensee = { id = "app.cash.licensee", version.ref = "gradlePlugins-licensee" }
gross = { id = "se.premex.gross", version.ref = "gradlePlugins-gross" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "gradlePlugins-kotlinxSerialization" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "gradlePlugins-detekt" }
sentry = { id = "io.sentry.android.gradle", version.ref = "gradlePlugins-sentry" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "gradlePlugins-ktlint" }

