name: build-wireguard-go

on:
  workflow_dispatch:
    inputs:
      os:
        required: true
        description: 'Runner'
        default: 'ubuntu-22.04'
        type: choice
        options:
        - ubuntu-20.04
        - ubuntu-22.04
        - macos-12
        - macos-13
        - macos-13-xlarge
        - macos-14
        - custom-runner-mac-m1
        - arc-runner-set

  # reusable workflow
  workflow_call:
    inputs:
      os:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      - name: 'Cleanup working directory'
        if: contains(inputs.os, 'custom')
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y git curl gcc g++ make
        if: inputs.os == 'arc-runner-set'

      - name: Checkout nym-vpn-client
        uses: actions/checkout@v4
        with:
          # fetch only the root files and wireguard dir
          sparse-checkout: |
            wireguard

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Build wireguard
        run: |
          go version
          go env
          cc -v
          gcc -v
          make -v
          perl -v
          ./wireguard/build-wireguard-go.sh

      - name: Upload artifacts (ubuntu-20.04 x86_64)
        uses: actions/upload-artifact@v4
        if: contains(inputs.os, 'ubuntu-20.04')
        with:
          name: wireguard-go_ubuntu-20.04_x86_64
          path: |
            build/lib/x86_64-unknown-linux-gnu
          retention-days: 1

      - name: Upload artifacts (ubuntu-22.04 x86_64)
        uses: actions/upload-artifact@v4
        if: contains(inputs.os, 'ubuntu-22.04') || inputs.os == 'arc-runner-set'
        with:
          name: wireguard-go_ubuntu-22.04_x86_64
          path: |
            build/lib/x86_64-unknown-linux-gnu
          retention-days: 1

      - name: Upload artifacts (macos x86_64)
        uses: actions/upload-artifact@v4
        if: inputs.os == 'macos-12' || inputs.os == 'macos-13'
        with:
          name: wireguard-go_macos_x86_64
          path: |
            build/lib/x86_64-apple-darwin
          retention-days: 1

      # On ARM we always build universal binaries now

      # - name: Upload artifacts (macos aarch64)
      #   uses: actions/upload-artifact@v4
      #   if: inputs.os == 'custom-runner-mac-m1' || inputs.os == 'macos-13-xlarge' || inputs.os == 'macos-14'
      #   with:
      #     name: wireguard-go_macos_aarch64
      #     path: |
      #       build/lib/aarch64-apple-darwin
      #     retention-days: 1

      - name: Upload artifacts (macos universal)
        uses: actions/upload-artifact@v4
        if: inputs.os == 'custom-runner-mac-m1' || inputs.os == 'macos-13-xlarge' || inputs.os == 'macos-14'
        with:
          name: wireguard-go_macos_universal
          path: |
            build/lib/universal-apple-darwin
          retention-days: 1
