name: build-mullvad-windows
on: [workflow_dispatch, workflow_call]

env:
  CARGO_TERM_COLOR: always

# https://github.com/actions/runner-images/issues/1794#issuecomment-707217728

jobs:
  build:
    runs-on: "custom-windows-11"

    steps:
      - name: Checkout mullvad libs for Windows
        uses: actions/checkout@v4
        with:
          repository: nymtech/nym-vpn-mullvad-libs
          ref: main
          path: "nym-vpn-mullvad-libs"
          submodules: true

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2

      # - name: Build/Move winfw from mullvad
      #   shell: bash
      #   run: |
      #     cd ${GITHUB_WORKSPACE}/nym-vpn-mullvad-libs
      #     CPP_BUILD_MODES=Release ./build-windows-modules.sh

      - name: Build/Move winfw from mullvad
        uses: nick-fields/retry@v3
        with:
          shell: bash
          timeout_seconds: 15
          max_attempts: 3
          retry_on: error
          command: |
            cd ${GITHUB_WORKSPACE}/nym-vpn-mullvad-libs
            CPP_BUILD_MODES=Release ./build-windows-modules.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: winfw.dll
          path: |
            ${{ github.workspace }}/nym-vpn-mullvad-libs/windows/winfw/bin/x64-Release/winfw.dll
          retention-days: 10

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: winfw.lib
          path: |
            ${{ github.workspace }}/nym-vpn-mullvad-libs/windows/winfw/bin/x64-Release/winfw.lib
          retention-days: 10
