name: build-wireguard-go

on:
  workflow_dispatch:
    inputs:
      os:
        required: true
        description: 'Runner'
        default: 'ubuntu-22.04'
        type: choice
        options:
        - ubuntu-20.04
        - ubuntu-22.04
        - macos-latest
        - custom-runner-mac-m1

  # reusable workflow
  workflow_call:
    inputs:
      os:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:
      - name: 'Cleanup working directory'
        if: contains(inputs.os, 'custom')
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout nym-vpn-client
        uses: actions/checkout@v4
        with:
          # fetch only the root files and wireguard dir
          sparse-checkout: |
            wireguard

      # TODO: check that this is actually used
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        if: contains(inputs.os, 'macos') || contains(inputs.os, 'mac-m1') || contains(inputs.os, 'windows')
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: Build wireguard
        run: ./wireguard/build-wireguard-go.sh

      - name: Upload artifacts (ubuntu 22.04 x86_64)
        uses: actions/upload-artifact@v4
        if: contains(inputs.os, 'ubuntu-22.04')
        with:
          name: wireguard-go_ubuntu-22.04_x86_64
          path: |
            build/lib/x86_64-unknown-linux-gnu

      - name: Upload artifacts (ubuntu 20.04 x86_64)
        uses: actions/upload-artifact@v4
        if: contains(inputs.os, 'ubuntu-20.04')
        with:
          name: wireguard-go_ubuntu-20.04_x86_64
          path: |
            build/lib/x86_64-unknown-linux-gnu

      - name: Upload artifacts (macos x86_64)
        uses: actions/upload-artifact@v4
        if: contains(inputs.os, 'macos')
        with:
          name: wireguard-go_macos_x86_64
          path: |
            build/lib/x86_64-apple-darwin

      - name: Upload artifacts (macos aarch64)
        uses: actions/upload-artifact@v4
        if: contains(inputs.os, 'mac-m1')
        with:
          name: wireguard-go_macos_aarch64
          path: |
            build/lib/aarch64-apple-darwin
