name: ci-nym-vpn-android

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "nym-vpn-core/**"
      - "nym-vpn-android/**"
      - ".github/workflows/ci-nym-vpn-android.yml"
      - ".github/workflows/build-nym-vpn-android.yml"
      - ".github/workflows/publish-nym-vpn-android.yml"

jobs:
  check:
    runs-on: ubuntu-22.04-arc
    defaults:
      run:
        working-directory: nym-vpn-android
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            nym-vpn-android
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;26.3.11579264"

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run detekt
        run: ./gradlew detekt --info

  build-nym-vpn-android:
    uses: ./.github/workflows/build-nym-vpn-android.yml
    with:
      build_type: 'debug'
