name: ci-nymvpn-x-js

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ci-nymvpn-x-js.yml"
      - "nym-vpn-x/**"

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04-arc, custom-windows-11]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            nym-vpn-x

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: nym-vpn-x/package-lock.json

      - name: Install dependencies
        working-directory: nym-vpn-x
        run: npm ci

      - name: Typecheck
        working-directory: nym-vpn-x
        run: npm run tscheck

      - name: Check lint
        working-directory: nym-vpn-x
        run: npm run lint

      - name: Check formatting
        working-directory: nym-vpn-x
        run: npm run fmt:ci

      #      - name: Run tests
      #        working-directory: nym-vpn-x
      #        run: npm run test

      - name: Check build
        working-directory: nym-vpn-x
        run: npm run build
