# TODO temp wf used to pull and install locally nym-hash-releases
# action from nymtech/nym repo
name: create-hashes-json

on:
  workflow_call:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true
        type: string

jobs:
  build:
    name: Create hashes.json
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout nym-hash-releases sources
      #   uses: actions/checkout@v4
      #   with:
      #     repository: nymtech/nym
      #     ref: bugfix/action-release
      #     sparse-checkout: |
      #       .github/actions/nym-hash-releases
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 18
      # - name: Install packages
      #   run: cd ./.github/actions/nym-hash-releases && npm i

      - uses: nymtech/nym/.github/actions/nym-hash-releases@bugfix/action-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo: nym-vpn-client
          release-tag-or-name-or-id: ${{ inputs.release_tag }}

      - uses: actions/upload-artifact@v2
        with:
          name: Asset Hashes
          path: hashes.json

